//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NewClass3.
    /// </summary>
    // *** Start programmer edit section *** (NewClass3 CustomAttributes)

    // *** End programmer edit section *** (NewClass3 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NewClass3 : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Test3.здание fздание;
        
        // *** Start programmer edit section *** (NewClass3 CustomMembers)

        // *** End programmer edit section *** (NewClass3 CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.Номер CustomAttributes)

        // *** End programmer edit section *** (NewClass3.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.Номер Get start)

                // *** End programmer edit section *** (NewClass3.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (NewClass3.Номер Get end)

                // *** End programmer edit section *** (NewClass3.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.Номер Set start)

                // *** End programmer edit section *** (NewClass3.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (NewClass3.Номер Set end)

                // *** End programmer edit section *** (NewClass3.Номер Set end)
            }
        }
        
        /// <summary>
        /// NewClass3.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.здание CustomAttributes)

        // *** End programmer edit section *** (NewClass3.здание CustomAttributes)
        [PropertyStorage(new string[] {
                "здание"})]
        [NotNull()]
        public virtual IIS.Test3.здание здание
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.здание Get start)

                // *** End programmer edit section *** (NewClass3.здание Get start)
                IIS.Test3.здание result = this.fздание;
                // *** Start programmer edit section *** (NewClass3.здание Get end)

                // *** End programmer edit section *** (NewClass3.здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.здание Set start)

                // *** End programmer edit section *** (NewClass3.здание Set start)
                this.fздание = value;
                // *** Start programmer edit section *** (NewClass3.здание Set end)

                // *** End programmer edit section *** (NewClass3.здание Set end)
            }
        }
    }
}
