//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// здание.
    /// </summary>
    // *** Start programmer edit section *** (здание CustomAttributes)

    // *** End programmer edit section *** (здание CustomAttributes)
    [AutoAltered()]
    [Caption("Здание")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class здание : ICSSoft.STORMNET.DataObject
    {
        
        private string fУлица;
        
        private string fНомерДома;
        
        private int fКоличествоЭтаж;
        
        private IIS.Test3.Город fГород;
        
        // *** Start programmer edit section *** (здание CustomMembers)

        // *** End programmer edit section *** (здание CustomMembers)

        
        /// <summary>
        /// КоличествоЭтаж.
        /// </summary>
        // *** Start programmer edit section *** (здание.КоличествоЭтаж CustomAttributes)

        // *** End programmer edit section *** (здание.КоличествоЭтаж CustomAttributes)
        public virtual int КоличествоЭтаж
        {
            get
            {
                // *** Start programmer edit section *** (здание.КоличествоЭтаж Get start)

                // *** End programmer edit section *** (здание.КоличествоЭтаж Get start)
                int result = this.fКоличествоЭтаж;
                // *** Start programmer edit section *** (здание.КоличествоЭтаж Get end)

                // *** End programmer edit section *** (здание.КоличествоЭтаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (здание.КоличествоЭтаж Set start)

                // *** End programmer edit section *** (здание.КоличествоЭтаж Set start)
                this.fКоличествоЭтаж = value;
                // *** Start programmer edit section *** (здание.КоличествоЭтаж Set end)

                // *** End programmer edit section *** (здание.КоличествоЭтаж Set end)
            }
        }
        
        /// <summary>
        /// НомерДома.
        /// </summary>
        // *** Start programmer edit section *** (здание.НомерДома CustomAttributes)

        // *** End programmer edit section *** (здание.НомерДома CustomAttributes)
        [StrLen(255)]
        public virtual string НомерДома
        {
            get
            {
                // *** Start programmer edit section *** (здание.НомерДома Get start)

                // *** End programmer edit section *** (здание.НомерДома Get start)
                string result = this.fНомерДома;
                // *** Start programmer edit section *** (здание.НомерДома Get end)

                // *** End programmer edit section *** (здание.НомерДома Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (здание.НомерДома Set start)

                // *** End programmer edit section *** (здание.НомерДома Set start)
                this.fНомерДома = value;
                // *** Start programmer edit section *** (здание.НомерДома Set end)

                // *** End programmer edit section *** (здание.НомерДома Set end)
            }
        }
        
        /// <summary>
        /// Улица.
        /// </summary>
        // *** Start programmer edit section *** (здание.Улица CustomAttributes)

        // *** End programmer edit section *** (здание.Улица CustomAttributes)
        [StrLen(255)]
        public virtual string Улица
        {
            get
            {
                // *** Start programmer edit section *** (здание.Улица Get start)

                // *** End programmer edit section *** (здание.Улица Get start)
                string result = this.fУлица;
                // *** Start programmer edit section *** (здание.Улица Get end)

                // *** End programmer edit section *** (здание.Улица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (здание.Улица Set start)

                // *** End programmer edit section *** (здание.Улица Set start)
                this.fУлица = value;
                // *** Start programmer edit section *** (здание.Улица Set end)

                // *** End programmer edit section *** (здание.Улица Set end)
            }
        }
        
        /// <summary>
        /// здание.
        /// </summary>
        // *** Start programmer edit section *** (здание.Город CustomAttributes)

        // *** End programmer edit section *** (здание.Город CustomAttributes)
        [PropertyStorage(new string[] {
                "Город"})]
        [NotNull()]
        public virtual IIS.Test3.Город Город
        {
            get
            {
                // *** Start programmer edit section *** (здание.Город Get start)

                // *** End programmer edit section *** (здание.Город Get start)
                IIS.Test3.Город result = this.fГород;
                // *** Start programmer edit section *** (здание.Город Get end)

                // *** End programmer edit section *** (здание.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (здание.Город Set start)

                // *** End programmer edit section *** (здание.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (здание.Город Set end)

                // *** End programmer edit section *** (здание.Город Set end)
            }
        }
    }
}
