//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Комната.
    /// </summary>
    // *** Start programmer edit section *** (Комната CustomAttributes)

    // *** End programmer edit section *** (Комната CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомнатаE", new string[] {
            "НомерКомнаты as \'Номер комнаты\'",
            "Этаж as \'Этаж\'",
            "Id as \'Id\'"})]
    [View("КомнатаL", new string[] {
            "НомерКомнаты as \'Номер комнаты\'",
            "Этаж as \'Этаж\'",
            "Id as \'Id\'"})]
    public class Комната : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКомнаты;
        
        private int fЭтаж;
        
        private int fId;
        
        // *** Start programmer edit section *** (Комната CustomMembers)

        // *** End programmer edit section *** (Комната CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Id CustomAttributes)

        // *** End programmer edit section *** (Комната.Id CustomAttributes)
        public virtual int Id
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Id Get start)

                // *** End programmer edit section *** (Комната.Id Get start)
                int result = this.fId;
                // *** Start programmer edit section *** (Комната.Id Get end)

                // *** End programmer edit section *** (Комната.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Id Set start)

                // *** End programmer edit section *** (Комната.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (Комната.Id Set end)

                // *** End programmer edit section *** (Комната.Id Set end)
            }
        }
        
        /// <summary>
        /// НомерКомнаты.
        /// </summary>
        // *** Start programmer edit section *** (Комната.НомерКомнаты CustomAttributes)

        // *** End programmer edit section *** (Комната.НомерКомнаты CustomAttributes)
        public virtual int НомерКомнаты
        {
            get
            {
                // *** Start programmer edit section *** (Комната.НомерКомнаты Get start)

                // *** End programmer edit section *** (Комната.НомерКомнаты Get start)
                int result = this.fНомерКомнаты;
                // *** Start programmer edit section *** (Комната.НомерКомнаты Get end)

                // *** End programmer edit section *** (Комната.НомерКомнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.НомерКомнаты Set start)

                // *** End programmer edit section *** (Комната.НомерКомнаты Set start)
                this.fНомерКомнаты = value;
                // *** Start programmer edit section *** (Комната.НомерКомнаты Set end)

                // *** End programmer edit section *** (Комната.НомерКомнаты Set end)
            }
        }
        
        /// <summary>
        /// Этаж.
        /// </summary>
        // *** Start programmer edit section *** (Комната.Этаж CustomAttributes)

        // *** End programmer edit section *** (Комната.Этаж CustomAttributes)
        public virtual int Этаж
        {
            get
            {
                // *** Start programmer edit section *** (Комната.Этаж Get start)

                // *** End programmer edit section *** (Комната.Этаж Get start)
                int result = this.fЭтаж;
                // *** Start programmer edit section *** (Комната.Этаж Get end)

                // *** End programmer edit section *** (Комната.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Комната.Этаж Set start)

                // *** End programmer edit section *** (Комната.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (Комната.Этаж Set end)

                // *** End programmer edit section *** (Комната.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомнатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатаE", typeof(IIS.Test3.Комната));
                }
            }
            
            /// <summary>
            /// "КомнатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомнатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомнатаL", typeof(IIS.Test3.Комната));
                }
            }
        }
    }
}
